"""empty message

Revision ID: 46b556c0b40b
Revises: 0fa5695f0587
Create Date: 2019-08-11 21:23:52.089413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46b556c0b40b'
down_revision = '0fa5695f0587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'client_key',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint('cart_ibfk_1', 'cart', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cart_ibfk_1', 'cart', 'client', ['client_key'], ['client_id'])
    op.alter_column('cart', 'client_key',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
